### PR TITLE
Add flatpak

### PR DESCRIPTION
**Pull request by GeopJr**
I don't think it's ready yet but here's a first try!

- aarch64 crystal binaries are maintained by me, I don't know if they have any other issues (I use crystal's distribution scripts to build them) but they seem to work nicely for Collision (https://github.com/geopjr-forks/crystal-aarch64)
- shards are generated from the lockfile + lib/ (for postscripts) using https://github.com/GeopJr/Collision/blob/main/data/scripts/shards_to_sources.cr
- building gi-crystal is a bit messy but it works
- I filled the metainfo file, some info might be wrong (I commented out the mobile ones as rtfm is not mobile-szie-friendly yet)

This is not flat**hub** ready yet:
- [x] figure out permissions (are glib docsets on host? can they be included in the flatpak instead of opening a hole in the sandbox?)
- [ ] use yaml for flat**hub**
- [ ] use x-checker-data for flat**hub** (auto checks and opens PRs when sources (rtfm) get new releases)
- [ ] set up a ci for nightly builds? (might be better after some specs are added)

you can give it a try on your machine by running:
```
$ flatpak-builder ./build ./data/io.github.hugopl.rtfm.json --user --install --force-clean
$ flatpak run io.github.hugopl.rtfm

### CODE REVIEW

**Comment by hugopl** [comment]
I plan to generate docsets for GTK libs (including Glib), but now only Crystal API are generated by `make docsets`.

Yep, I need to set up a CI, at least to check if it's building... 

I have no experience in building flatpack packages at all (or even running them), so initially I would like to keep flatpack specific files in a separated folder, could be `/packages/flatpack`. Is this .json file specific for flatpack generation? The metadata XML file too? If so would be nice to move them away from `data/` dir.

**Comment by GeopJr** [comment]
The flatpak should be self-contained (just the .json, unless you want to move the shard-sources generator script from collision here). The metainfo file, while required by flat**hub**, other distributions can use it too for their software centers (https://freedesktop.org/software/appstream/docs/chap-Quickstart.html), it contains metadata about the app (author, screenshots, license, age rating, changelog etc.). Having the .json file in the repo (instead of just directly submitting it to flat**hub**), allows people to run RTFM in GNOME Builder.

I'll set up the CI for the flatpak after some specs are done or the initial crystal ci is added

**Comment by hugopl** [comment]
Does `flatpak-builder` use a sandbox to build the flatpack package? If so I wonder how the docsets will be generated by it, since it depends on files installed by other packages like the gtk docs.

**Comment by GeopJr** [comment]
Yes it does (that's why we need to include crystal and its runtime dependencies). The GNOME runtime is here https://gitlab.gnome.org/GNOME/gnome-build-meta and it splits the docs into a separate extension. I bumped the PR it seems to work fine!

If you are building the flatpak manually it will probably ask you to install the extension, either pass `--install-deps-from=flathub` to automatically install any missing deps or install the extension manually `flatpak install --user org.gnome.Sdk.Docs/x86_64/44`

image

**Comment by hugopl** [comment]
nice, I'll try to build this next time I touch rtfm and merge this.

And maybe release a 0.2.0.

**Comment by hugopl** [comment]
I had the feeling of being downloading an entire new distro through flatpack, but it worked!!

**Pull request merged**
